// Problem 2: Even Fibonacci Numbers

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

function fiboEvenSum(n) {
  let fibonacci = [1,2];
  for ( let i = 2; i < n; i++){
    fibonacci[i] = fibonacci[i-1] + fibonacci[i-2];
  }
  let sum = 0;
  for ( let j = 0; j < fibonacci.length; j++){
    if ( fibonacci[j] <= n && fibonacci[j] % 2 == 0){
      sum += fibonacci[j];
    } 
  }
  return sum;
}

console.log(fiboEvenSum(8));
console.log(fiboEvenSum(10));
console.log(fiboEvenSum(34));
console.log(fiboEvenSum(60));
console.log(fiboEvenSum(1000));
console.log(fiboEvenSum(100000));
console.log(fiboEvenSum(4000000));